import type { IBlog } from "@/types";

// ? DUMMY DATA FOR FEED PAGE 

export const blogs: IBlog[] = [
    {
        _id: "1",
        title: "The Evolution of Modern Web Development",
        body: "In the past decade, web development has undergone a radical transformation. From static HTML pages to dynamic single-page applications...",
        image: "https://picsum.photos/id/1015/800/400",
        author: {
            _id: "u1",
            username: "alexjohnson",
            email: "alex.johnson@example.com",
            password: "hashedpassword",
            bio: "Full-stack developer passionate about frontend performance.",
            profilePicture: "https://randomuser.me/api/portraits/men/45.jpg",
            followers: ["u2", "u3"],
            following: ["u5"],
            saves: [],
            userBlogs: ["1"],
            createdAt: new Date("2023-01-01"),
            updatedAt: new Date("2023-06-01"),
        },
        likes: ["u2", "u3", "u4"],
        comments: ["c1", "c2", "c3"],
        createdAt: new Date("2023-06-20T14:30:00Z"),
        updatedAt: new Date("2023-06-25T10:00:00Z"),
    },
    {
        _id: "2",
        title: "Understanding TypeScript: A Comprehensive Guide",
        body: "TypeScript has become an essential tool for modern web development...",
        image: "https://picsum.photos/id/1025/800/400",
        author: {
            _id: "u2",
            username: "mariachen",
            email: "maria.chen@example.com",
            password: "hashedpassword",
            bio: "Frontend engineer and TypeScript enthusiast.",
            profilePicture: "https://randomuser.me/api/portraits/women/32.jpg",
            followers: ["u1"],
            following: ["u3"],
            saves: [],
            userBlogs: ["2"],
            createdAt: new Date("2023-02-15"),
            updatedAt: new Date("2023-05-01"),
        },
        likes: ["u1", "u3", "u5"],
        comments: ["c4", "c5"],
        createdAt: new Date("2023-05-15T09:15:00Z"),
        updatedAt: new Date("2023-05-18T12:00:00Z"),
    },
    {
        _id: "3",
        title: "Exploring the Power of Serverless Architecture",
        body: "Serverless computing eliminates the need for managing servers...",
        image: "https://picsum.photos/id/1003/800/400",
        author: {
            _id: "u3",
            username: "noahkim",
            email: "noah.kim@example.com",
            password: "hashedpassword",
            bio: "Cloud engineer exploring serverless and distributed systems.",
            profilePicture: "https://randomuser.me/api/portraits/men/21.jpg",
            followers: ["u1", "u2"],
            following: ["u4"],
            saves: [],
            userBlogs: ["3"],
            createdAt: new Date("2023-04-01"),
            updatedAt: new Date("2023-07-01"),
        },
        likes: ["u1", "u2", "u4"],
        comments: ["c6"],
        createdAt: new Date("2024-01-08T12:45:00Z"),
        updatedAt: new Date("2024-01-10T10:30:00Z"),
    },
    {
        _id: "4",
        title: "Why You Should Care About Web Performance in 2025",
        body: "Performance is a ranking factor, a UX must-have, and a conversion booster...",
        image: "https://picsum.photos/id/1044/800/400",
        author: {
            _id: "u4",
            username: "emilypark",
            email: "emily.park@example.com",
            password: "hashedpassword",
            bio: "Frontend performance advocate and UX researcher.",
            profilePicture: "https://randomuser.me/api/portraits/women/68.jpg",
            followers: ["u1", "u3"],
            following: ["u5"],
            saves: [],
            userBlogs: ["4"],
            createdAt: new Date("2023-06-01"),
            updatedAt: new Date("2023-12-01"),
        },
        likes: ["u1", "u2", "u3", "u5"],
        comments: ["c7", "c8"],
        createdAt: new Date("2024-12-03T16:00:00Z"),
        updatedAt: new Date("2024-12-05T11:00:00Z"),
    },
    {
        _id: "5",
        title: "Top 10 VS Code Extensions to Boost Productivity",
        body: "Visual Studio Code is one of the most popular code editors today...",
        image: "https://picsum.photos/id/1050/800/400",
        author: {
            _id: "u5",
            username: "leofernandez",
            email: "leo.fernandez@example.com",
            password: "hashedpassword",
            bio: "Productivity hacker & VS Code power user.",
            profilePicture: "https://randomuser.me/api/portraits/men/54.jpg",
            followers: ["u2"],
            following: ["u1", "u3"],
            saves: [],
            userBlogs: ["5"],
            createdAt: new Date("2023-08-01"),
            updatedAt: new Date("2025-01-01"),
        },
        likes: ["u2", "u4", "u3"],
        comments: ["c9", "c10", "c11"],
        createdAt: new Date("2025-07-10T11:00:00Z"),
        updatedAt: new Date("2025-07-12T09:30:00Z"),
    },
    // ✅ New blogs
    {
        _id: "6",
        title: "Mastering React Hooks in 2025",
        body: "Hooks like useState, useEffect, and useMemo remain essential for React developers...",
        image: "https://picsum.photos/id/1070/800/400",
        author: {
            _id: "u6",
            username: "sofiabrown",
            email: "sofia.brown@example.com",
            password: "hashedpassword",
            bio: "React developer focusing on scalable frontend architecture.",
            profilePicture: "https://randomuser.me/api/portraits/women/12.jpg",
            followers: ["u1", "u5"],
            following: ["u2"],
            saves: [],
            userBlogs: ["6"],
            createdAt: new Date("2024-03-12"),
            updatedAt: new Date("2025-02-01"),
        },
        likes: ["u1", "u3", "u4", "u5"],
        comments: ["c12", "c13"],
        createdAt: new Date("2025-02-10T15:20:00Z"),
        updatedAt: new Date("2025-02-12T10:00:00Z"),
    },
    {
        _id: "7",
        title: "AI-Powered Development Tools: The Future of Coding",
        body: "AI tools like GitHub Copilot and ChatGPT are transforming how developers code...",
        image: "https://picsum.photos/id/1084/800/400",
        author: {
            _id: "u7",
            username: "ryantaylor",
            email: "ryan.taylor@example.com",
            password: "hashedpassword",
            bio: "Exploring the intersection of AI and software engineering.",
            profilePicture: "https://randomuser.me/api/portraits/men/36.jpg",
            followers: ["u2", "u6"],
            following: ["u1"],
            saves: [],
            userBlogs: ["7"],
            createdAt: new Date("2024-05-01"),
            updatedAt: new Date("2025-04-01"),
        },
        likes: ["u1", "u2", "u3", "u5", "u6"],
        comments: ["c14", "c15", "c16", "c17"],
        createdAt: new Date("2025-04-15T18:00:00Z"),
        updatedAt: new Date("2025-04-18T12:00:00Z"),
    },
    {
        _id: "8",
        title: "GraphQL vs REST: Which API Style Wins in 2025?",
        body: "Developers continue debating REST vs GraphQL. This article explores pros and cons of each...",
        image: "https://picsum.photos/id/1099/800/400",
        author: {
            _id: "u8",
            username: "oliviawright",
            email: "olivia.wright@example.com",
            password: "hashedpassword",
            bio: "Backend engineer specialized in GraphQL and API design.",
            profilePicture: "https://randomuser.me/api/portraits/women/29.jpg",
            followers: ["u3", "u6", "u7"],
            following: ["u4"],
            saves: [],
            userBlogs: ["8"],
            createdAt: new Date("2024-07-10"),
            updatedAt: new Date("2025-05-20"),
        },
        likes: ["u1", "u2", "u3", "u4", "u5", "u7"],
        comments: ["c18", "c19"],
        createdAt: new Date("2025-05-21T09:45:00Z"),
        updatedAt: new Date("2025-05-23T08:00:00Z"),
    },
];

export const trendingTopics = [
    { name: "#ReactJS", posts: "12.5K" },
    { name: "#TypeScript", posts: "8.2K" },
    { name: "#NextJS", posts: "6.7K" },
    { name: "#WebDev", posts: "5.9K" },
    { name: "#AI", posts: "15.3K" },
];

export const suggestedUsers = [
    { name: "Sarah Williams", avatar: "https://randomuser.me/api/portraits/women/44.jpg", role: "Frontend Lead" },
    { name: "Michael Chen", avatar: "https://randomuser.me/api/portraits/men/33.jpg", role: "UX Engineer" },
    { name: "Priya Patel", avatar: "https://randomuser.me/api/portraits/women/65.jpg", role: "React Specialist" },
];